import { GetUserProfileApiResponse } from '../../api/profile';

export enum ProfileConstants {
  FETCH_PROFILE_POSTS_REQUEST = 'profile/FETCH_PROFILE_POSTS_REQUEST',
  FETCH_PROFILE_POSTS_SUCCESS = 'profile/FETCH_PROFILE_POSTS_SUCCESS',
  FETCH_PROFILE_POSTS_FAILURE = 'profile/FETCH_PROFILE_POSTS_FAILURE',

  SET_PROFILE_STATUS_REQUEST = 'profile/SET_PROFILE_STATUS_REQUEST',
  SET_PROFILE_STATUS_SUCCESS = 'profile/SET_PROFILE_STATUS_SUCCESS',
  SET_PROFILE_STATUS_FAILURE = 'profile/SET_PROFILE_STATUS_FAILURE',

  FETCH_PROFILE_REQUEST = 'profile/FETCH_PROFILE_REQUEST',
  FETCH_PROFILE_SUCCESS = 'profile/FETCH_PROFILE_SUCCESS',
  FETCH_PROFILE_FAILURE = 'profile/FETCH_PROFILE_FAILURE',

  SET_PROFILE_PHOTO_REQUEST = 'profile/SET_PROFILE_PHOTO_REQUEST',
  SET_PROFILE_PHOTO_SUCCESS = 'profile/SET_PROFILE_PHOTO_SUCCESS',
  SET_PROFILE_PHOTO_FAILURE = 'profile/SET_PROFILE_PHOTO_FAILURE',

  SET_PROFILE_REQUEST = 'profile/SET_PROFILE_REQUEST',
  SET_PROFILE_SUCCESS = 'profile/SET_PROFILE_SUCCESS',
  SET_PROFILE_FAILURE = 'profile/SET_PROFILE_FAILURE',

  TOGGLE_FOLLOW_ON_PROFILE_REQUEST = 'profile/TOGGLE_FOLLOW_ON_PROFILE_REQUEST',
  TOGGLE_FOLLOW_ON_PROFILE_SUCCESS = 'profile/TOGGLE_FOLLOW_ON_PROFILE_SUCCESS',
  TOGGLE_FOLLOW_ON_PROFILE_FAILURE = 'profile/TOGGLE_FOLLOW_ON_PROFILE_FAILURE',

  CLEAR_PROFILE_STATE = 'profile/CLEAR_PROFILE_STATE',
}

export interface ProfilePost {
  id: number;
  title: string;
  body: string;
}

export interface UserProfile extends GetUserProfileApiResponse {
  followed: boolean;
}
